--- 
kind: pipeline
name: LolzClang
steps: 
  - 
    commands: 
      - "apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison ca-certificates ccache clang cmake curl file flex gcc g++ git libelf-dev libssl-dev make ninja-build python3 texinfo u-boot-tools zlib1g-dev"
      - "bash build_lolz.sh"
    image: "ubuntu:18.04"
    name: LolzClang
    trigger: 
      branch: 
        - master
