--- 
kind: pipeline
name: LolzClang
steps: 
  - 
    commands:
      - "apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison build-essential ca-certificates ccache clang cmake curl file flex gcc g++ git lld libelf-dev libssl-dev make ninja-build patchelf python3 texinfo u-boot-tools zlib1g-dev"
      - "bash build_lolz.sh"
    environment: 
      TOKEN: 
        from_secret: token
    image: "ubuntu:19.10"
    name: clang_builder
    trigger: 
      branch: 
        - master
